faction_creations: 0
enchants:
  # Specifies the location enchants are shown. Options: name, lore
  position: "name"
  # Toggles roman numerals for displaying enchantment levels
  roman-numerals: true
  # Toggles PiggyCE enchantment books
  books: true
# Toggles forms for /ce command