<?php



declare(strict_types = 1);

namespace vale\sage\demonic\entitys;

use pocketmine\item\{Item, enchantment\Enchantment, enchantment\EnchantmentInstance, ItemFactory, ItemIds};
use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Living;
use pocketmine\inventory\ArmorInventory;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\network\mcpe\protocol\MobEquipmentPacket;
use pocketmine\network\mcpe\protocol\types\entity\EntityIds;

class EntityBase extends Living{


	const NETWORK_ID = EntityIds::WITHER_SKELETON;

	public $width = 0.7;
	public $height = 2.4;

	public function getName(): string{
		return "an Envoy Guardian";
	}

	protected function initEntity(CompoundTag $nbt): void
	{
		parent::initEntity($nbt); // TODO: Change the autogenerated stub
	}

	public function getDrops(): array{
		return [
			ItemFactory::getInstance()->get(ItemIds::COAL),
			ItemFactory::getInstance()->get(ItemIds::BONE)
		];
	}

	protected function getInitialSizeInfo(): EntitySizeInfo
	{
		return new EntitySizeInfo(1,1,1);
	}

	public static function getNetworkTypeId(): string
	{
		return EntityIds::WITHER_SKELETON;
	}
}
